export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_CODE = "CREATE_CODE";
export const UPDATE_CODE = "UPDATE_CODE";
export const DELETE_CODE = "DELETE_CODE";
export const GET_CODES = "GET_CODES";
export const CODES_LOADING = "CODES_LOADING";
export const FIND_CODE = "FIND_CODE";

export const UPDATE_USER = "UPDATE_USER";
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";

export const GET_MACHINES = "GET_MACHINES";
export const CREATE_MACHINE = "CREATE_MACHINE";
export const UPDATE_MACHINE = "UPDATE_MACHINE";
export const DELETE_MACHINE = "DELETE_MACHINE";
export const MACHINES_LOADING = "MACHINES_LOADING";

export const NEW_RESERVATION = "NEW_RESERVATION";
export const GET_UPCOMING_RESERVATIONS = "GET_UPCOMING_RESERVATIONS";
export const GET_PAST_RESERVATIONS = "GET_PAST_RESERVATIONS";
export const PAST_RESERVATIONS_LOADING = "PAST_RESERVATIONS_LOADING";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const RESERVATIONS_LOADING = "RESERVATIONS_LOADING";

export const LOAD_AGENDA_DATA = "LOAD_AGENDA_DATA";
export const PREV_CLICK = "PREV_CLICK";
export const NEXT_CLICK = "NEXT_CLICK";
export const ON_VIEW_CHANGE = "ON_VIEW_CHANGE";
export const ON_SELECT_DATE = "ON_SELECT_DATE";
export const NEW_EVENT = "NEW_EVENT";
export const ON_SCROLL_RIGHT = "ON_SCROLL_RIGHT";
export const ON_SCROLL_LEFT = "ON_SCROLL_LEFT";